### ISSUE TITLE
Suggestion: Title font size

### ISSUE THREAD

**Issue by mohdumar-mern-dev** [mohdumar-mern/github#2]
# This looks better if changed title size to 48 to looks more better

```css
.title{
font-size: 48px:
}

```
